version: '3.4'
 
services:
 
  postgresql_database:
    container_name: postgre_container
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin@123
      - POSTGRES_DB=sampleDB
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
     
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=sample@somemail.com
      - PGADMIN_DEFAULT_PASSWORD=Admin@123
    ports:
      - "5051:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
 
volumes:
  database-data:
  pgadmin: